class AddKeys < ActiveRecord::Migration
  def change
    add_foreign_key "content_page_elements", "content_pages", :name => "content_page_elements_content_page_id_fk"
    add_foreign_key "content_pages_lessons", "content_pages", :name => "content_pages_lessons_content_page_id_fk"
    add_foreign_key "content_pages_lessons", "lessons", :name => "content_pages_lessons_lesson_id_fk"
    add_foreign_key "courses_learning_modules", "courses", :name => "courses_learning_modules_course_id_fk"
    add_foreign_key "courses_learning_modules", "learning_modules", :name => "courses_learning_modules_learning_module_id_fk"
    add_foreign_key "learning_modules_lessons", "learning_modules", :name => "learning_modules_lessons_learning_module_id_fk"
    add_foreign_key "learning_modules_lessons", "lessons", :name => "learning_modules_lessons_lesson_id_fk"
    add_foreign_key "morphed_photos", "user_details", :name => "morphed_photos_user_detail_id_fk"
    add_foreign_key "orgs_courses", "courses", :name => "orgs_courses_course_id_fk"
    add_foreign_key "orgs_courses", "orgs", :name => "orgs_courses_org_id_fk"
    add_foreign_key "question_grade_reports", "questions", :name => "question_grade_reports_question_id_fk"
    add_foreign_key "question_grade_reports", "quiz_results", :name => "question_grade_reports_quiz_result_id_fk"
    add_foreign_key "question_responses", "users", :name => "question_responses_user_id_fk"
    add_foreign_key "quiz_results", "quizzes", :name => "quiz_results_quiz_id_fk"
    add_foreign_key "quiz_results", "users", :name => "quiz_results_user_id_fk"
    add_foreign_key "quizzes_questions", "questions", :name => "quizzes_questions_question_id_fk"
    add_foreign_key "quizzes_questions", "quizzes", :name => "quizzes_questions_quiz_id_fk"
    add_foreign_key "redactor_assets", "users", :name => "redactor_assets_user_id_fk"
    add_foreign_key "text_blocks", "courses", :name => "text_blocks_course_id_fk"
    add_foreign_key "text_blocks", "learning_modules", :name => "text_blocks_learning_module_id_fk"
    add_foreign_key "text_blocks", "lessons", :name => "text_blocks_lesson_id_fk"
    add_foreign_key "user_details", "users", :name => "user_details_user_id_fk"
    add_foreign_key "users_courses", "courses", :name => "users_courses_course_id_fk"
    add_foreign_key "users_courses", "users", :name => "users_courses_user_id_fk"
    add_foreign_key "users", "orgs", :name => "users_org_id_fk"
  end
end
